name: K8s Audit on Minikube

on:
  push:
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install tools (minikube, kubectl, trivy...)
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          sudo apt-get update
          sudo apt-get install -y kubectl
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash

      - name: Start Minikube
        run: minikube start --driver=docker

      - name: Run Security Audit
        run: bash scripts/run_all_audits.sh

      - name: Upload audit reports
        uses: actions/upload-artifact@v4
        with:
          name: audit-reports
          path: reports/
